# 3. Getting Started



## 3.1 Python

In [1]:
import sys
# Check Python version
if sys.version_info.major == 3 and sys.version_info.minor >=6:
  print("Hello, World!")
  print(f"Python version: {sys.version}")
else:
  print("Please use Python 3.6 or higher.")

Hello, World!
Python version: 3.12.12 (main, Oct 10 2025, 08:52:57) [GCC 11.4.0]


## 3.2 Data Types

In [2]:
# Mutable Data Type
my_list = [1, 2, 3]
print("Original List:", my_list)
# Modifying the list
my_list.append(4)
print("Modified List:", my_list)
# Immutable Data Type (Tuple)
my_tuple = (1, 2, 3)
print("Original Tuple:", my_tuple)
# Trying to modify the tuple (will raise an error)
# my_tuple.append(4) # Uncommenting this line will raise an AttributeError

Original List: [1, 2, 3]
Modified List: [1, 2, 3, 4]
Original Tuple: (1, 2, 3)


### Numeric Data

In [3]:
age = 23 #int
pi = 3.14 #float
temperature = -5.5 #float
print("data type of variable age = ", type(age))
print("data type of variable pi = ", type(pi))
print("data type of variable temperature = ", type(temperature))

data type of variable age =  <class 'int'>
data type of variable pi =  <class 'float'>
data type of variable temperature =  <class 'float'>


###Sequence data

In [4]:
# str
name = "John"
greeting = 'Hello'
address = "Kathmandu"
print("data type of the variable name = ",type(name))
print("data type of the variable greeting = ",type(greeting))
print("data type of the variable address = ",type(address))
# slice only one element
print("The first letter of the name is:", name[0])
print("The last letter of the name is:", name[-1])
# slice a range of elements
print("The second letter to the fourth of the name is:", name[1:4])
print("The first two letters of the name are:", name[:2])
print("Substring starting from the third letter is:", name[2:])

data type of the variable name =  <class 'str'>
data type of the variable greeting =  <class 'str'>
data type of the variable address =  <class 'str'>
The first letter of the name is: J
The last letter of the name is: n
The second letter to the fourth of the name is: ohn
The first two letters of the name are: Jo
Substring starting from the third letter is: hn


In [5]:
# list
list1 = [1, 2, 3, 4]
mixed_list = [12, "Hello", True]
# List is mutable
mixed_list[0] = False
mixed_list

[False, 'Hello', True]

In [6]:
# tuple
colors = ('red', 'green', 'yellow', 'blue')
print("First element:", colors[0])
print("Last two elements:", colors[2:])
print("Middle two elements:", colors[1:3])
# colors[0] = 'purple'
colors # will generate an error as tuple is immutable.

First element: red
Last two elements: ('yellow', 'blue')
Middle two elements: ('green', 'yellow')


('red', 'green', 'yellow', 'blue')

In [105]:
# dict
person = {'name':'Rahi','age':33,'city':'Dang'}
print(f"Hello my name is {person['name']}. I am {person['age']} years old and I live in {person['city']}.")
print("All keys:", list(person.keys()))
print("All values:", list(person.values()))

Hello my name is Rahi. I am 33 years old and I live in Dang.
All keys: ['name', 'age', 'city']
All values: ['Rahi', 33, 'Dang']


In [8]:
# set
unique_numbers = {1,2,3,3,3,3,4,5}
print(unique_numbers)

{1, 2, 3, 4, 5}


In [9]:
# boolean
is_student = True
has_license = False
print ("data type of the variable is_student = ", type(is_student))
print("data type of the variable has_license = ", type(has_license))

data type of the variable is_student =  <class 'bool'>
data type of the variable has_license =  <class 'bool'>


In [10]:
# special
result = None

## 3.3 Logical Statements and Loops

In [11]:
# if-else statement
num = -10
if num > 0:
  print("Positive")
elif num == 0:
  print("Zero")
else:
  print("Non-positive")

Non-positive


In [12]:
# Comparision Operator
x=5
y=10
if x >0 and y<20:
  print("Both conditions are true")
if x >0 or y>20:
  print("At least one condition is true")
if not x==0:
  print("x is not equal to 0")

Both conditions are true
At least one condition is true
x is not equal to 0


In [13]:
# Logical Operator
# Define two boolean variables
a = True
b = False
# Using the ’and’ operator
if a and b:
  print("Both a and b are True")
else:
  print("Either a or b is False") # This will be printed
# Using the ’or’ operator
if a or b:
  print("At least one of a or b is True") # This will be printed
else:
  print("Both a and b are False")
# Using the ’not’ operator
if not a:
  print("a is False") # This will not be printed
else:
  print("a is True") # This will be printed

Either a or b is False
At least one of a or b is True
a is True


In [14]:
# Loops
# for loop:
fruits = ["apple", "banana","cherry"]
for fruit in fruits:
  print(fruit)
# While loop:
count = 0
while count < 5:
  print("Count is:", count)
  count += 1
# Break
fruits = ["apple", "banana", "orange"]
print("loop 1")
for fruit in fruits:
  print(fruit)
  if fruit == "apple":
    break
# Continue
print("loop 2")
for fruit in fruits:
  if fruit == "apple":
    continue
  else:
    print(fruit)

apple
banana
cherry
Count is: 0
Count is: 1
Count is: 2
Count is: 3
Count is: 4
loop 1
apple
loop 2
banana
orange


## 3.5 Functions, 3.6 Anatomy of Function

In [15]:
# function example
def add_binary(a, b):
  '''
  Returns the sum of two decimal numbers in binary digits.
  Parameters:
  a (int): A decimal integer
  b (int): Another decimal integer
  Returns:
  binary_sum (str): Binary string of the sum of a and b
  '''
  binary_sum = bin(a+b)[2:]
  return binary_sum
result = add_binary(10, 20)
print(result)

11110


In [16]:
# Built - in - Function
print("Hello, World!") # Output: Hello, World!
length = len("Hello") # Output: 5
data_type = type(42) # Output: <class 'int'>
total = sum([1, 2, 3]) # Output: 6
# Built- in-Methods
# str.upper(): Converts all characters in a string to uppercase.
message = "hello".upper() # Output: "HELLO"
# list.append(): Adds an element to the end of a list.
fruits = ["apple", "banana"]
fruits.append("cherry") # Output: ["apple", "banana", "cherry"]
# dict.get(): Returns the value associated with a key in a dictionary.
info = {"name": "John", "age": 25}
age = info.get("age") # Output: 25

Hello, World!


In [17]:
# User-Defined function
def temperature_converter():
  """
  Converts temperature between Celsius and Fahrenheit.
  This function prompts the user to specify the conversion type (Celsius to Fahrenheit or
  Fahrenheit to Celsius)
  and then asks for the temperature value. It calculates and returns the converted temperature.
  Returns:
  float: The converted temperature value.
  """
  print("Choose conversion type:")
  print("1. Celsius to Fahrenheit")
  print("2. Fahrenheit to Celsius")
  # Get conversion choice from user
  choice = input("Enter 1 or 2: ")
  if choice == "1":
    # Celsius to Fahrenheit conversion
    celsius = float(input("Enter temperature in Celsius: "))
    fahrenheit = (celsius * 9/5) + 32
    print(f"{celsius}C is equal to {fahrenheit}F")
    return fahrenheit
  elif choice == "2":
    # Fahrenheit to Celsius conversion
    fahrenheit = float(input("Enter temperature in Fahrenheit: "))
    celsius = (fahrenheit - 32) * 5/9
    print(f"{fahrenheit}F is equal to {celsius}C")
    return celsius
  else:
    print("Invalid choice. Please enter 1 or 2.")
    return None
# Call the function
temperature_converter()

Choose conversion type:
1. Celsius to Fahrenheit
2. Fahrenheit to Celsius
Enter 1 or 2: 2
Enter temperature in Fahrenheit: 2
2.0F is equal to -16.666666666666668C


-16.666666666666668

## 3.7  Global and Local Variables:

In [18]:
x = 10 # Global Variable.
def print_global():
  print(x) # Accessing global variable
print_global() # Output: 10

10


In [19]:
def print_local():
  y = 5 # Local variable
  print(y)
print_local() # Output: 5
# print(y) #causes anerror because the y is declared inside the function

5


In [20]:
x = 10 # Global variable
def modify_global():
  global x # Declaring x as global
  x = 20 # Modifying global x
  modify_global()
print(x) # Output: 20

10


## 3.8 Exception and Error Handling

### Types of Error

In [21]:
# syntax error
# print("Hello) # python parses finds it before the program runs (usually)

In [22]:
# Exceptions
# result = 10 / 0 # also called run-time error

###  try-except

In [23]:
#Handling exceptions
try:
  num = int(input("Enter a number: "))
  print("Result:", 10 / num)
except ZeroDivisionError:
  print("Cannot divide by zero.")
except ValueError:
  print("Invalid input. Please enter a number.")

Enter a number: 3
Result: 3.3333333333333335


### finally block

In [24]:
try:
  file = open("example.txt", "r")
  data = file.read()
except FileNotFoundError:
  print("File not found.")
finally:
  print("the final block")
  # file.close() # Ensures the file is closed

File not found.
the final block


### Raising Custom Exceptions

In [25]:
def check_age(age):
  if age < 0:
    raise ValueError("Age cannot be negative.")
  else:
    print("Valid age")
try:
  check_age(-1)
except ValueError as e:
  print(e)

Age cannot be negative.


# 4. To do Task

## 4.1 Exercise on Functions:

### Task -1:

In [26]:
def convert_units(type, value):
    """
    Convert the values between different units of measurement

    Parameters:
    type (int): Type of conversion selected
    value (float): The value to be converted

    Returns:
    float: The value after conversion
    """

    conversions = {
        1: value * 3.28084,     # meters to feet
        2: value / 3.28084,     # feet to meters
        3: value * 2.20462,     # kg to lbs
        4: value / 2.20462,     # lbs to kg
        5: value * 0.264172,    # liters to gallons
        6: value / 0.264172     # gallons to liters
    }

    return conversions.get(type)


print("----------Unit Conversion----------")
print("------------------------------------")
print("1. Meters (m) to Feet (ft)")
print("2. Feet (ft) to Meters (m)")
print("3. Kilograms (kg) to Pounds (lbs)")
print("4. Pounds (lbs) to Kilograms (kg)")
print("5. Liters (L) to Gallons (gal)")
print("6. Gallons (gal) to Liters (L)")

try:
    choice = int(input("Choose a conversion (1-6): "))

    if choice not in range(1, 7):
        print("Option out or range")

    else:
        value = float(input("Enter the value to convert: "))
        result = convert_units(choice, value)

        print("Converted value:", round(result, 3)) # rounding up the result

except ValueError:
    print("Invalid input. Please enter a numeric value.")

----------Unit Conversion----------
------------------------------------
1. Meters (m) to Feet (ft)
2. Feet (ft) to Meters (m)
3. Kilograms (kg) to Pounds (lbs)
4. Pounds (lbs) to Kilograms (kg)
5. Liters (L) to Gallons (gal)
6. Gallons (gal) to Liters (L)
Choose a conversion (1-6): 5
Enter the value to convert: 2
Converted value: 0.528


### Task 2:

In [27]:
def calculate_sum(numbers):
    """
    Calculate the sum of a list of numbers

    Parameters:
    numbers (list): A list of numeric values

    Returns:
    float: The sum of the numbers
    """
    total = 0
    for num in numbers:
        total += num
    return total


def calculate_average(numbers):
    """
    Calculate the average of a list of numbers

    Parameters:
    numbers (list): A list of numeric values

    Returns:
    float: The average of the numbers
    """
    return calculate_sum(numbers) / len(numbers)


def find_max(numbers):
    """
    Find the maximum value in a list of numbers

    Parameters:
    numbers (list): A list of numeric values

    Returns:
    float: The largest number in the list
    """
    maximum = numbers[0]
    for num in numbers:
        if num > maximum:
            maximum = num
    return maximum


def find_min(numbers):
    """
    Find the minimum value in a list of numbers

    Parameters:
    numbers (list): A list of numeric values

    Returns:
    float: The smallest number in the list
    """
    minimum = numbers[0]
    for num in numbers:
        if num < minimum:
            minimum = num
    return minimum


print("Choose an operation:")
print("1 Sum")
print("2 Average")
print("3 Maximum")
print("4 Minimum")

try:
    choice = int(input("Enter your choice (1-4): "))

    numbers_input = input("Enter numbers separated by spaces: ")
    numbers = [float(num) for num in numbers_input.split()] # split by empty space

    if len(numbers) == 0:
        raise ValueError("List cannot be empty")

    if choice == 1:
        result = calculate_sum(numbers)
        print("Sum =", result)

    elif choice == 2:
        result = calculate_average(numbers)
        print("Average =", result)

    elif choice == 3:
        result = find_max(numbers)
        print("Maximum =", result)

    elif choice == 4:
        result = find_min(numbers)
        print("Minimum =", result)

    else:
        print("Invalid operation choice")

except ValueError:
    print("Invalid input. Please enter numeric values separated by spaces")

Choose an operation:
1 Sum
2 Average
3 Maximum
4 Minimum
Enter your choice (1-4): 3
Enter numbers separated by spaces: 2
Maximum = 2.0


## 4.2  Exercise on List Manipulation:

### 1. Extract Every Other Element:

In [28]:
def extract_every_other(lst):
    result = []
    for i in range(0, len(lst), 2):
        result.append(lst[i])
    return result

lst = [2, 4, 6, 8, 10]
print(extract_every_other(lst))

[2, 6, 10]


### 2. Slice a Sublist:

In [29]:
def get_sublist(lst, start, end):
  return lst[start:end+1]
lst = [1, 2, 3, 4, 5, 6]
sublist = get_sublist(lst, 1, 4)
print(sublist)

[2, 3, 4, 5]


### 3. Reverse a List Using Slicing:

In [30]:
def reverse_list(lst):
  return lst[::-1]
lst = [1, 2, 3, 4]
reversed_lst = reverse_list(lst)
print(reversed_lst)

[4, 3, 2, 1]


### 4. Remove the First and Last Elements:

In [31]:
def remove_first_last(lst):
  return lst[1:-1]
lst = [1, 2, 3, 4, 5]
result = remove_first_last(lst)
print(result)

[2, 3, 4]


### 5. Get the First n Elements:

In [32]:
def get_first_n(lst, n):
  return lst[0:n]
lst=[1,2,3,4,5]
result=get_first_n(lst,2)
print(result)

[1, 2]


### 6. Extract Elements from the End:

In [33]:
def get_last_n(lst,n):
  return lst[-n:]
lst=[1,2,3,4,5]
result=get_last_n(lst,2)
print(result)

[4, 5]


### 7. Extract Elements in Reverse Order:

In [34]:
def reverse_skip(lst):
  return lst[::-2]
lst=[1,2,3,4,5]
result=reverse_skip(lst)
print(result)

[5, 3, 1]


## 4.3 Exercise on Nested List:

### 1. Flatten a Nested List

In [35]:
def flatten(lst):
  flattened = []
  for item in lst:
    if isinstance(item, list):
      flattened.extend(flatten(item))
    else:
      flattened.append(item)
  return flattened
nested_list = [1, [2, 3], [4, [5, 6]]]
flattened_list = flatten(nested_list)
print(flattened_list)

[1, 2, 3, 4, 5, 6]


### 2. Accessing Nested List Elements

In [36]:
def access_nested_element(lst, indices):
    element = lst
    for i in indices:
        element = element[i]
    return element

lst = [[10, 20, 30], [40, 50, 60], [70, 80, 90]]
indices = [2, 1]
print(access_nested_element(lst, indices))

80


### 3. Sum of All Elements in a Nested List

In [37]:
def sum_nested(lst):
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total

lst = [[2, 4], [6, [8, 10]], 12]
print(sum_nested(lst))

42


### 4. Remove Specific Element from a Nested List

In [38]:
def remove_element(lst, elem):
    result = []

    for item in lst:
        if isinstance(item, list):
            result.append(remove_element(item, elem))
        elif item != elem:
            result.append(item)

    return result

lst = [[3, 5], [7, 5], [9, 11]]
elem = 5
print(remove_element(lst, elem))

[[3], [7], [9, 11]]


### 5. Find the Maximum Element in a Nested List

In [39]:
def find_max_element(lst):
    maximum = float('-inf')

    for item in lst:
        if isinstance(item, list):
            maximum = max(maximum, find_max_element(item))
        else:
            maximum = max(maximum, item)

    return maximum

lst = [[12, 4], [18, [7, 25]], 9]
print(find_max_element(lst))

25


### 6. Count Occurrences of an Element in a Nested List

In [40]:
def count_occurrences(lst, elem):
    count = 0

    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1

    return count
lst = [[4, 6], [6, 8], [6, 10]]
elem = 6
print(count_occurrences(lst, elem))

3


### 7. Flatten a List of Lists of Lists

In [41]:
def deep_flatten(lst):
    result = []

    for item in lst:
        if isinstance(item, list):
            result.extend(deep_flatten(item))
        else:
            result.append(item)

    return result

lst = [[[2, 4], [6, 8]], [[10, 12], [14, 16]]]
print(deep_flatten(lst))

[2, 4, 6, 8, 10, 12, 14, 16]


### 8. Nested List Average

In [42]:
def average_nested(lst):
    def helper(lst):
        total = 0
        count = 0
        for item in lst:
            if isinstance(item, list):
                t, c = helper(item)
                total += t
                count += c
            else:
                total += item
                count += 1

        return total, count
    total, count = helper(lst)
    return total / count

lst = [[5, 10], [15, 20], [25, 30]]
print(average_nested(lst))

17.5


# 5. Numpy

##Getting Start

## 6.1 Introduction to Array ndarray:

In [43]:
import numpy as np
# initialize an all zero array with size 2 X 3:
zeros_arr = np.zeros ((2,3))
print(" A zeros array is \n", zeros_arr, "with dimensions", zeros_arr.shape, "\n")

 A zeros array is 
 [[0. 0. 0.]
 [0. 0. 0.]] with dimensions (2, 3) 



In [44]:
import numpy as np
# Create and display zero, one, and n-dimensional arrays
zero_dim_array = np.array(5)
one_dim_array = np.array([1, 2, 3])
n_dim_array = np.array([[1, 2], [3, 4]])
for arr in [zero_dim_array, one_dim_array, n_dim_array]:
  print(f"Array:\n{arr}\nDimension: {arr.ndim}\nData type: {arr.dtype}\n")

Array:
5
Dimension: 0
Data type: int64

Array:
[1 2 3]
Dimension: 1
Data type: int64

Array:
[[1 2]
 [3 4]]
Dimension: 2
Data type: int64



### 6.1.1 Some of the key attributes of ndarray:

In [45]:
# dimensions
# For a 1-D array:
import numpy as np
arr_1d = np.array([1, 2, 3, 4, 5])
print(arr_1d.ndim) # Output: 1
# For a 2-D array:
arr_2d = np.array([[1, 2, 3],
[4, 5, 6]])
print(arr_2d.ndim) # Output: 2
#For a 3-D array:
arr_3d = np.array([[[1, 2, 3],
[4, 5, 6]],
[[7, 8, 9],
[10, 11, 12]]])
print(arr_3d.ndim) # Output: 3

1
2
3


In [46]:
# shape
print(arr_1d.shape) # Output: (5,)
print(arr_2d.shape) # Output: (2, 3)
print(arr_3d.shape) # Output: (2, 2, 3)

(5,)
(2, 3)
(2, 2, 3)


In [47]:
# size - Total Number of Elements:
print(arr_1d.size) # Output: 5
print(arr_2d.size) # Output: 6
print(arr_3d.size) # Output: 12

5
6
12


In [48]:
print("--------data type---------")
print(arr_1d.dtype) # Output: int64 (or int32)
arr_float = np.array([1.1, 2.2, 3.3])
print(arr_float.dtype) # Output: float64
print("--------item size---------")
print(arr_1d.itemsize) # Output: 8 (for int64)
print("--------memory consumption---------")
print(arr_1d.nbytes) # Output: 40 (5 elements \times 8 bytes each for int64)
print("--------array transpose---------")
print(arr_2d.T)
# Output:
# [[1 4]
# [2 5]
# [3 6]]
print("--------array flattening---------")
for item in arr_2d.flat:
  print(item, end=" ") # Output: 1 2 3 4 5 6
print("--------real and Imaginary Parts---------")
arr_complex = np.array([1+2j, 3+4j])
print(arr_complex.real) # Output: [1. 3.]
print(arr_complex.imag) # Output: [2. 4.]
print("--------data conversion---------")
arr_float = arr_2d.astype(float)
print(arr_float)
# Output:
# [[1. 2. 3.]
# [4. 5. 6.]]

--------data type---------
int64
float64
--------item size---------
8
--------memory consumption---------
40
--------array transpose---------
[[1 4]
 [2 5]
 [3 6]]
--------array flattening---------
1 2 3 4 5 6 --------real and Imaginary Parts---------
[1. 3.]
[2. 4.]
--------data conversion---------
[[1. 2. 3.]
 [4. 5. 6.]]


### 6.1.2 Common Errors with Key Attributes

In [49]:
# attribute error
lst = [[1, 2], [3, 4]]
# print(lst.shape)
# Error: List has no .shape attribute
#Fixing the Error:
arr = np.array(lst)
print(arr.shape) # Output: (2, 2)

(2, 2)


In [50]:
# index error
arr = np.array([1, 2, 3])
# print(arr.shape[1]) # Error: 1D array only has one dimension
# Fixing the Error
if len(arr.shape) > 1:
  print(arr.shape[1]) # Access only if it’s valid

In [51]:
# type error
arr = np.array([[1, 2, 3], [4, 5, 6]])
# print(arr.shape()) # Error: .shape is an attribute, not a function
print(arr.shape) # Correct usage

(2, 3)


In [52]:
# value error
a = np.array([[1, 2], [3, 4]])
b = np.array([1, 2, 3])
# print(a + b) # Error: Shapes (2,2) and (3,) are not compatible

In [53]:
#large_array = np.ones((100000, 100000)) # Caused MemoryError

### 6.1.3 NumPy ndarray- reshape:

In [54]:
import numpy as np
# Create an array with shape (2, 3)
array = np.array([[1, 2, 3],
[4, 5, 6]])

# Reshape to (3, 2), keeping 6 elements
reshaped_array = array.reshape(3, 2)
print("Original Shape:", array.shape, "\nReshaped Shape:", reshaped_array.shape)
# Expected Outputs:
# Original Shape: (2, 3)
# Reshaped Shape: (3, 2)

Original Shape: (2, 3) 
Reshaped Shape: (3, 2)


In [55]:
array = np.array([[1, 2, 3], [4, 5, 6]])
# reshaped_array = array.reshape(4, 2)
# Error: cannot reshape array of size 6 into shape (4, 2)

In [56]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


# 7. How to Create an Array {ndarray}?

## Intro

In [57]:
import numpy as np
a = np.arange(1, 10)
print(a)
x = range(1, 10)
print(x) # x is an iterator
print(list(x))
# further arange examples:
x = np.arange(10.4)
print(x)
x = np.arange(0.5, 10.4, 0.8)
print(x)

[1 2 3 4 5 6 7 8 9]
range(1, 10)
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 0.5  1.3  2.1  2.9  3.7  4.5  5.3  6.1  6.9  7.7  8.5  9.3 10.1]


In [58]:
import numpy as np
# 50 values between 1 and 10:
print(np.linspace(1, 10))
# 7 values between 1 and 10:
print(np.linspace(1, 10, 7))
# excluding the endpoint:
print(np.linspace(1, 10, 7, endpoint=False))

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]
[ 1.   2.5  4.   5.5  7.   8.5 10. ]
[1.         2.28571429 3.57142857 4.85714286 6.14285714 7.42857143
 8.71428571]


In [59]:
import numpy as np
# Create arrays of specified shapes
ones_array = np.ones((2, 3)) # Shape: (2, 3)
zeros_array = np.zeros((3, 2)) # Shape: (3, 2)
empty_array = np.empty((2, 2)) # Shape: (2, 2)
identity_matrix = np.eye(3) # Shape: (3, 3)
print(ones_array, zeros_array, empty_array, identity_matrix, sep='\n\n')

[[1. 1. 1.]
 [1. 1. 1.]]

[[0. 0.]
 [0. 0.]
 [0. 0.]]

[[4.9e-324 9.9e-324]
 [1.5e-323 2.0e-323]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [60]:
import numpy as np
array_from_list = np.array([1, 2, 3]) # [1 2 3]
array_from_tuple = np.array((4, 5, 6)) # [4 5 6]
array_from_nested_list = np.array([[1, 2, 3], [4, 5, 6]]) # [[1 2 3] [4 5 6]]
print(array_from_list, array_from_tuple, array_from_nested_list, sep='\n')

[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]


In [61]:
import numpy as np
# Existing Array of Shape:(2,3)
arr = np.array([[1, 2, 3], [4, 5, 6]])
# Creating Array with Shape of existing array:
zeros, ones, empty = np.zeros(arr.shape), np.ones(arr.shape), np.empty(arr.shape) #
Shape: (2,3)
print(arr, zeros, ones, empty, sep='\n')

[[1 2 3]
 [4 5 6]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[7.828e-319 0.000e+000 0.000e+000]
 [0.000e+000 0.000e+000 0.000e+000]]


In [62]:
import numpy as np
arr1 = np.array([[1, 2], [3, 4]]) # Shape: (2, 2)
arr2 = np.array([[5, 6], [7, 8]]) # Shape: (2, 2)
# Stacking examples
hstacked = np.hstack((arr1, arr2))
# Output hstack: [[1 2 5 6] [3 4 7 8]]
vstacked = np.vstack((arr1, arr2))
# Output vstack[[1 2] [3 4] [5 6] [7 8]]
colstacked = np.column_stack((arr1[0], arr2[0]))
# Output column stack: [[1 5] [2 6]]
print(hstacked, vstacked, colstacked, sep='\n')

[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 5]
 [2 6]]


In [63]:
import numpy as np
# Creating two 3D arrays
arr1 = np.array([[[1], [2]], [[3], [4]]]) # Shape: (2, 2, 1)
arr2 = np.array([[[5], [6]], [[7], [8]]]) # Shape: (2, 2, 1)
# Concatenate along axis 0 (vertical stacking)
concat_axis0 = np.concatenate((arr1, arr2), axis=0)
# Shape of concat_axis0: (4, 2, 1), arr1 is stacked on top of arr2
# Concatenate along axis 1 (horizontal stacking)
concat_axis1 = np.concatenate((arr1, arr2), axis=1)
# Shape of concat_axis1: (2, 4, 1), arr1 and arr2 are placed side by side
# Concatenate along axis 2 (depth stacking)
concat_axis2 = np.concatenate((arr1, arr2), axis=2)
# Shape of concat_axis2: (2, 2, 2), arr1 and arr2 are stacked in depth (third dimension)
# Displaying the results
print("Concatenation along axis 0 (Vertical stacking):\n", concat_axis0)
print("Shape of concatenated array along axis 0:", concat_axis0.shape)
print("\nConcatenation along axis 1 (Horizontal stacking):\n", concat_axis1)
print("Shape of concatenated array along axis 1:", concat_axis1.shape)
print("\nConcatenation along axis 2 (Depth stacking):\n", concat_axis2)
print("Shape of concatenated array along axis 2:", concat_axis2.shape)

Concatenation along axis 0 (Vertical stacking):
 [[[1]
  [2]]

 [[3]
  [4]]

 [[5]
  [6]]

 [[7]
  [8]]]
Shape of concatenated array along axis 0: (4, 2, 1)

Concatenation along axis 1 (Horizontal stacking):
 [[[1]
  [2]
  [5]
  [6]]

 [[3]
  [4]
  [7]
  [8]]]
Shape of concatenated array along axis 1: (2, 4, 1)

Concatenation along axis 2 (Depth stacking):
 [[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]
Shape of concatenated array along axis 2: (2, 2, 2)


## 7.2 Key Errors in Array Combining Operations: Causes and Solutions:

In [64]:
import numpy as np
# Incorrect shapes
arr1 = np.array([[1, 2], [3, 4]]) # shape (2, 2)
arr2 = np.array([5, 6]) # shape (2,)
# Attempting horizontal stack
try:
  hstacked = np.hstack((arr1, arr2)) # Error due to dimension mismatch
except ValueError as e:
  print(f"Error: {e}")
# Solution: Reshape arr2 to match arr1’s dimensions
arr2 = np.array([5, 6]).reshape(2, 1) # shape (2, 1)
hstacked = np.hstack((arr1, arr2)) # No error
print(hstacked)

Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
[[1 2 5]
 [3 4 6]]


In [65]:
import numpy as np
arr1 = np.array([[1, 2, 3], [4, 5, 6]]) # shape (2, 3)
arr2 = np.array([[7, 8], [9, 10]]) # shape (2, 2)
# Attempting horizontal stack (this will fail)
try:
  hstacked = np.hstack((arr1, arr2)) # Error due to shape mismatch
except ValueError as e:
  print(f"Error: {e}")
# Solution: Make sure the number of rows in both arrays is the same before stacking
arr2 = np.array([[7, 8, 9], [10, 11, 12]]) # shape (2, 3)
hstacked = np.hstack((arr1, arr2)) # Works fine
print(hstacked)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [66]:
arr1 = np.array([[1, 2], [3, 4]], dtype=int)
arr2 = np.array([[5, 6], [7, 8]], dtype=float)
# Attempting horizontal stack (this will work, but can lead to unexpected results)
# hstacked = np.hstack((arr1, arr2))
# print(hstacked)
# Solution: Convert the data types to match each other explicitly, if needed:
arr2 = np.array([[5, 6], [7, 8]], dtype=int) # Match the type of arr1
hstacked = np.hstack((arr1, arr2)) # Works fine
print(hstacked)

[[1 2 5 6]
 [3 4 7 8]]


In [67]:
arr1 = np.array([[[1, 2], [3, 4]]]) # shape (1, 2, 2)
arr2 = np.array([[5, 6], [7, 8]]) # shape (2, 2)
# Attempting stacking with 3D and 2D arrays
try:
  vstacked = np.vstack((arr1, arr2)) # Error due to too many dimensions
except ValueError as e:
  print(f"Error: {e}")
# Solution: Reshape arr1 to be 2D (or flatten it) before stacking
arr1 = arr1.reshape(2, 2) # Now it’s shape (2, 2)
vstacked = np.vstack((arr1, arr2)) # Works fine
print(vstacked)

Error: all the input arrays must have same number of dimensions, but the array at index 0 has 3 dimension(s) and the array at index 1 has 2 dimension(s)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


# 8. Array Slicing and Indexing

In [68]:
import numpy as np
# Creating a 2D array
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# Accessing elements using indexing
print(array[0, 1]) # Output: 2 (first row, second column)
print(array[-1, -1]) # Output: 9 (last row, last column)
# Slicing the array
print(array[0:2, 1:3]) # Output: [[2, 3], [5, 6]]

2
9
[[2 3]
 [5 6]]


## 8.1 Index Out of Bounds Error:

In [69]:
import numpy as np
# Creating a 2D array
array = np.array([[1, 2, 3], [4, 5, 6]])
# Attempting to access an element out of bounds
try:
  print(array[2, 1])
except IndexError as e:
  print(f"Error: {e}")

Error: index 2 is out of bounds for axis 0 with size 2


# 9. Array Mathematics with NumPy.

## 9.1 Universal Functions{ufuncs}:

In [70]:
import numpy as np
# Example of basic ufuncs: square and square root
arr = np.array([1, 4, 9, 16])
# Square every element
squared = np.square(arr)
# Square root of every element
sqrt = np.sqrt(arr)
print(f"Squared: {squared}")
print(f"Square root: {sqrt}")

Squared: [  1  16  81 256]
Square root: [1. 2. 3. 4.]


In [71]:
# mathematics ufuncs
import numpy as np
# Trigonometric ufuncs
angles = np.array([0, np.pi / 4, np.pi / 2])
sine_values = np.sin(angles)
# Logarithmic ufuncs
log_values = np.log(arr)

## 9.2 Linear Algebra with np.linalg.

In [72]:
import numpy as np
# Matrix multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
product = np.dot(A, B)
# Compute determinant
det = np.linalg.det(A)
# Compute inverse
inverse = np.linalg.inv(A)
# Compute eigenvalues and eigenvectors
eigvals, eigvecs = np.linalg.eig(A)
print(f"Matrix Product:\n{product}")
print(f"Determinant: {det}")
print(f"Inverse:\n{inverse}")
print(f"Eigenvalues: {eigvals}, Eigenvectors:\n{eigvecs}")

Matrix Product:
[[19 22]
 [43 50]]
Determinant: -2.0000000000000004
Inverse:
[[-2.   1. ]
 [ 1.5 -0.5]]
Eigenvalues: [-0.37228132  5.37228132], Eigenvectors:
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


## 9.3 Broadcasting:

In [73]:
# Column Matches
import numpy as np
A = np.array([[1], [2], [3]]) # Shape (3,1) 3 rows, 1 column
B = np.array([10, 20, 30]) # Shape (3,) 1D array (3 elements)
C = A + B # Works! Result shape: (3,3)
print(C)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [74]:
# row matches
A = np.array([[1, 2, 3]]) # Shape (1,3)
B = np.array([[4], [5], [6]]) # Shape (3,1)
C = A + B #Works! Result shape: (3,3)
print(C)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [75]:
# dimension mismatch
A = np.ones((3,2)) # Shape (3,2)
B = np.ones((2,3)) # Shape (2,3)
#C = A + B #ValueError: operands could not be broadcast together

## 9.4 Vectorization:

In [76]:
# Python vs NumPy
import numpy as np
import time
# Create two large arrays
size = 10**6
a = np.random.rand(size)
b = np.random.rand(size)
# Using a loop
start_time = time.time()
result_loop = np.zeros(size)
for i in range(size):
  result_loop[i] = a[i] + b[i]
end_time = time.time()
loop_time = end_time - start_time
print(f"Loop Execution Time: {loop_time:.5f} seconds")
# Using NumPy’s vectorized operations
start_time = time.time()
result_vectorized = a + b # Element-wise addition
end_time = time.time()
vectorized_time = end_time - start_time
print(f"Vectorized Execution Time: {vectorized_time:.5f} seconds")
# Performance improvement factor
speedup = loop_time / vectorized_time
print(f"Vectorization is approximately {speedup:.2f} times faster!")

Loop Execution Time: 0.50366 seconds
Vectorized Execution Time: 0.00495 seconds
Vectorization is approximately 101.67 times faster!


# 10. To do NumPy

## 10.1 Basic Vector and Matrix Operation with Numpy.

### Problem- 1: Array Creation:

In [77]:
import numpy as np

In [78]:
arr1 = np.empty((2,2)) # empty array
print(arr1)
print("-------------")
arr2 = np.ones((4,2)) # all one array
print(arr2)

[[2.5e-323 3.0e-323]
 [3.5e-323 4.0e-323]]
-------------
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [79]:
arr3 = np.full((3,3), 5)
print(arr3)
print("-------------")
arr4 = np.zeros_like(arr3)
print(arr4)
print("-------------")
arr5 = np.ones_like(arr3)
print(arr5)

[[5 5 5]
 [5 5 5]
 [5 5 5]]
-------------
[[0 0 0]
 [0 0 0]
 [0 0 0]]
-------------
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [80]:
new_list = [1,2,3,4]
a = np.array(new_list)
print(a)

[1 2 3 4]


### Problem- 2: Array Manipulation: Numerical Ranges and Array indexing:

In [81]:
arr = np.arange(10,50)
print(arr)
print("-------------")
matrix = np.arange(9).reshape(3,3)
print("\n3 x 3 array from 0-8: ",matrix)
print("-------------")
identity_matrix = np.eye(3)
print("\nIdentity matrix: ", identity_matrix)
print("-------------")
rand_arr = np.random.random(30)
print(rand_arr)
print("\nMean:", rand_arr.mean())
print("-------------")
arr = np.random.random((10,10))
print("Min:", arr.min())
print("Max:", arr.max())

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
-------------

3 x 3 array from 0-8:  [[0 1 2]
 [3 4 5]
 [6 7 8]]
-------------

Identity matrix:  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
-------------
[0.77675658 0.01250762 0.51584186 0.3275021  0.88890374 0.55320757
 0.98472495 0.5756353  0.9815162  0.48743023 0.075272   0.3220927
 0.07266426 0.84752336 0.16127611 0.32743624 0.82277978 0.79032597
 0.55270224 0.42113296 0.36095293 0.437738   0.16516135 0.97990279
 0.10788485 0.70247145 0.07889139 0.52466357 0.18031755 0.11643454]

Mean: 0.47172167348712357
-------------
Min: 0.003588352302035358
Max: 0.9911802735859416


In [82]:
arr = np.zeros(10)
arr[4] = 1
print(arr)
print("-------------")
arr = np.array([1,2,0,0,4,0])
rev = arr[::-1]
print("\nReverse array: ",rev)
print("-------------")
arr = np.ones((5,5))
arr[1:-1,1:-1] = 0
print(arr)
print("-------------")
board = np.zeros((8,8),dtype=int)
board[1::2, ::2] = 1
board[::2, 1::2] = 1
print(board)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
-------------

Reverse array:  [0 4 0 0 2 1]
-------------
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
-------------
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### Problem- 3: Array Operations:

In [83]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11,12])

In [84]:
# Add two arrays
print(x + y)
print("-------------")
# Subtract two arrays
print(x - y)
print("-------------")
#Multiply with integer
print(x * 3)
print("-------------")
# Square of each element
print(x ** 2)

[[ 6  8]
 [10 13]]
-------------
[[-4 -4]
 [-4 -3]]
-------------
[[ 3  6]
 [ 9 15]]
-------------
[[ 1  4]
 [ 9 25]]


In [85]:
# Dot product
print("Dot product of: ")
print("v & w: ")
print(np.dot(v,w))
print("x & v: ")
print(np.dot(x,v))
print("x & y: ")
print(np.dot(x,y))

Dot product of: 
v & w: 
219
x & v: 
[29 77]
x & y: 
[[19 22]
 [50 58]]


In [86]:
# Concatenate
print("Row-wise (x and y): ")
print(np.concatenate((x,y), axis=0))
print("Column-wise (v and w): ")
print(np.vstack((v,w)).T)
print("Concatenate x and v: ")
# np.concatenate((x,v)) # Raises ValueError: all the input arrays must have same number of dimensions

Row-wise (x and y): 
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
Column-wise (v and w): 
[[ 9 11]
 [10 12]]
Concatenate x and v: 


### Problem- 4: Matrix Operations:

In [87]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

In [88]:
A_inv = np.linalg.inv(A)
I = np.dot(A, A_inv)
print(I)

[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [89]:
AB = np.dot(A,B)
BA = np.dot(B,A)

print("AB =\n", AB)
print("BA =\n", BA)

AB =
 [[23 13]
 [51 29]]
BA =
 [[36 44]
 [13 16]]


In [90]:
left = np.dot(A,B).T
right = np.dot(B.T, A.T)

print(left)
print(right)

[[23 51]
 [13 29]]
[[23 51]
 [13 29]]


In [91]:
# Linear equations
A = np.array([
    [2,-3,1],
    [1,-1,2],
    [3,1,-1]
])
B = np.array([-1,-3,9])

print("Using inverse method: ")
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
print("Solution:", X)

Using inverse method: 
Solution: [ 2.  1. -2.]


## 10.2 Experiment: How Fast is Numpy?

In [92]:
import time

### 1. Element-wise Addition:

In [93]:
#Python List
size = 1000000

list1 = list(range(size))
list2 = list(range(size))

start_py = time.time()
result = [list1[i] + list2[i] for i in range(size)]
end_py = time.time()

In [94]:
# NumPy
a = np.arange(size)
b = np.arange(size)

start_np = time.time()
result = a + b
end_np = time.time()

In [95]:
#Comparison
print("Python list addition time:", end_py-start_py)
print("NumPy addition time:", end_np-start_np)

Python list addition time: 0.1179192066192627
NumPy addition time: 0.01931929588317871


### 2. Element-wise Multiplication

In [96]:
# Python List
start_py = time.time()
result = [list1[i] * list2[i] for i in range(size)]
end_py = time.time()

In [97]:
# NumPy
start_np = time.time()
result = a * b
end_np = time.time()

In [98]:
# Execution Time
print("Python list multiplication:", end_py-start_py)
print("NumPy multiplication:", end_np-start_np)

Python list multiplication: 0.11878275871276855
NumPy multiplication: 0.019482135772705078


### 3. Dot Product

In [99]:
# Python List
start_py = time.time()
dot = sum(list1[i] * list2[i] for i in range(size))
end_py = time.time()

In [100]:
# NumPy
start_np = time.time()
dot = np.dot(a,b)
end_np = time.time()

In [101]:
# Execution Time
print("Python dot product: ", end_py-start_py)
print("NumPy dot product:", end_np-start_np)

Python dot product:  0.14166593551635742
NumPy dot product: 0.002592325210571289


### 4. Matrix Multiplication

In [102]:
# Python Lists
size = 100

A = [[1]*size for _ in range(size)]
B = [[1]*size for _ in range(size)]

start_py = time.time()
result = [[sum(A[i][k]*B[k][j] for k in range(size))
           for j in range(size)] for i in range(size)]
end_py = time.time()

In [103]:
# NumPy
A = np.ones((1000,1000))
B = np.ones((1000,1000))

start_np = time.time()
C = np.dot(A,B)
end_np = time.time()

In [104]:
print("Python matrix multiplication:", end_py-start_py)
print("NumPy matrix multiplication:", end_np-start_np)

Python matrix multiplication: 0.19165682792663574
NumPy matrix multiplication: 0.10520291328430176
